package com.example.brockapp

//constants used for locations samples

const val CUSTOM_INTENT_USER_ACTION = "USER-ACTIVITY-DETECTION-INTENT-ACTION"
const val CUSTOM_REQUEST_CODE_USER_ACTION = 1000
const val DATABASE_NAME = "BrockDB"
const val DATABASE_VERSION = 1
//const val CUSTOM_INTENT_GEOFENCE = "GEOFENCE-TRANSITION-INTENT-ACTION"
//const val CUSTOM_REQUEST_CODE_GEOFENCE = 1001