package com.example.brockapp

const val SIGN_IN_ERROR = "CREDENZIALI PRESENTI, SEI SICURO DI NON AVERE GIÀ UN ACCOUNT?"
const val LOGIN_ERROR = "CREDENZIALI ERRATE, SEI SICURO DI AVERE UN ACCOUNT?"
const val BLANK_ERROR = "INSERISCI USERNAME E PASSWORD PER EFFETTUARE L'ACCESSO."

const val ROOM_DATABASE_VERSION = 12

const val REQUEST_CODE_PERMISSION_ACTIVITY_RECOGNITION = 1001
const val REQUEST_CODE_BROADCAST_RECEIVER = 1010

const val CHARTS_DATE_FORMAT = "MM-yyyy"

const val DATE_SEPARATOR = "-"
const val CALENDAR_DATE_FORMAT = "yyyy-MM-dd"
const val DATE_FORMAT = "dd-MM-yyyy HH:mm:ss"
const val UNIVERSAL_DATE = "d-M-yyyy"
